Capstone1
adeola003/Ruby-on-rails-bootcamp pull request #1
Opened 2023-03-15 17:31 UTC by adeola003

This project required a good working plan. Here are the detailed steps that led me to get this project finished:
**1- HTML skeleton:**
- I built the HTML skeleton of the website following the given template;
- I created two distinct HTML files for the two main pages;
- I used semantics tags and arranged my code following the HTM best practices;
**2- Styling**
- I created two distinct CSS files for the two main pages;
- I imported bootstrap and used some bootstrap classes for basic styling;
- I customized the styling to match the template by adding more CSS rules;
**3- Javascript**
- I used javascript at first to make the navigation bar button switch automatically from opening to closing;
- In the second part, I generated the speakers' section of the website using javascript as per the project requirements;
**4- Finishing the project**
-I updated the README file and added the MIT license. I also gave credit to the original designer.
- I added HTML, CSS, and JS linters and fixed linters errors;
- You will find a short video where I present the features of this project by clicking [here](https://www.loom.com/share/eba929c7995740e6ace508a9c6984b66)

2023-03-15 18:09 UTC, Lizdev-05 requested changes
Hi @adeola003, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<img src="https://media4.giphy.com/media/T1WqKkLY753dZghbu6/giphy.gif"/>
## Invalid Code Review Request

You have submitted a project, that does not have complete README sections. Kindly update your README file and resubmit

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-15 18:17 UTC, adeola003 commented
Hello, @Lizdev-05. I do not understand what changes are required on the README file. Can you please tell me what I need to do exactly?

2023-03-15 18:25 UTC, adeola003 commented
![3](https://user-images.githubusercontent.com/119133987/225406786-a049e6da-cfd0-44e3-ac32-866128995648.PNG)
![4](https://user-images.githubusercontent.com/119133987/225406793-2b6a4e34-023b-42c9-b8e2-9283981f7ba4.PNG)
![5](https://user-images.githubusercontent.com/119133987/225406798-60c64586-4a62-4977-b2af-6cc0d056c5ea.PNG)
![1](https://user-images.githubusercontent.com/119133987/225406803-c3372dac-59ac-42c2-b773-7684df6d1870.PNG)
![2](https://user-images.githubusercontent.com/119133987/225406805-d633c757-8644-4d7b-af95-bda3c9eb44e8.PNG)
Here is the current look of my README file

2023-03-15 20:19 UTC, Lizdev-05 requested changes
Hi @adeola003, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Suggested changes

- [x] Kindly make use of the same colors, text, backgrounds, borders, etc, like what we have in the original design 🥺

 
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-15 20:19 UTC, Lizdev-05 commented on README.md
> +
Great job so far 👍. Kindly add the live link to this section so that users can have access to the live demo of the project. Here is what we have presently 
<img width="910" alt="image" src="https://user-images.githubusercontent.com/73854999/225420244-1b1cad3e-e740-4009-8240-1776a351972e.png">

2023-03-15 20:19 UTC, Lizdev-05 commented on README.md
> +
Kindly add the platform on which you deployed your application, is it the GitHub Page or Netlify? Kindly, specify.  This will make your work to be well documented. 😊

2023-03-15 20:19 UTC, Lizdev-05 commented on index.html
> +      </nav>
Great job adding the nav bar. 👍 
Kindly make sure that the nav has the same padding on both the left and right as we have it in the design.
| Your Design | Behance Design |
| :---:   | :---: | 
|<img width="1470" alt="image" src="https://user-images.githubusercontent.com/73854999/225422307-9216f12c-cc23-4c4f-9d18-bdc6a2d92c25.png"> | <img width="1013" alt="image" src="https://user-images.githubusercontent.com/73854999/225422197-2e9e0821-8bd1-463e-81a8-949284e28780.png">|

2023-03-15 20:19 UTC, Lizdev-05 commented on index.html
> +
Kindly add more left-padding to your content section and use the Typography: font face, size, and weight like what we have in the design... 🥺 
| Your Design | Figma Design |
| :---:   | :---: | 
| <img width="1470" alt="image" src="https://user-images.githubusercontent.com/73854999/225423021-2755de14-cbcd-4f56-8623-2ff162322377.png">|<img width="1021" alt="image" src="https://user-images.githubusercontent.com/73854999/225423301-629a099a-f0a4-4b9d-99b3-dbbe90845473.png"> |

2023-03-15 20:19 UTC, Lizdev-05 commented on index.html
> +  </section>
Great job adding the schedule section 👍. Kindly make sure that the cards have the same height also, it will be good if you can reduce the margin between the cards so that we can achieve the same design as what we have in the design  🥺 .
| Your Design | Figma Design |
| :---:   | :---: | 
| <img width="1470" alt="image" src="https://user-images.githubusercontent.com/73854999/225424493-712beb28-31fc-4cbf-a7b7-e16344ee4c1e.png">| <img width="1021" alt="image" src="https://user-images.githubusercontent.com/73854999/225424397-f8c3d08b-0b5f-4efd-8ee8-e0a403b32634.png">|

2023-03-15 20:19 UTC, Lizdev-05 commented on index.html
> +        </ul>
Kindly make use of the same color, styling and font as we have in the design 🥺 
| Your Design | Figma Design |
| :---:   | :---: | 
| <img width="1458" alt="image" src="https://user-images.githubusercontent.com/73854999/225425323-f41ab5db-cd42-4edd-882a-9c0734cb31e5.png">|<img width="1029" alt="image" src="https://user-images.githubusercontent.com/73854999/225425215-75da5721-f168-4baa-947b-709242ef1f3c.png">|

2023-03-15 20:19 UTC, Lizdev-05 commented on index.html
> +  </footer>
Kindly give your footer the necessary padding and margin. 🥺 
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/73854999/225425543-cb9aa3c3-b431-4083-a299-4a338ec2e472.png"> 

Also, according to the requirement, your footer should contain a logo at the left and text at the right. Kindly add the logo and the necessary stylings. 🥺

2023-03-15 20:19 UTC, Lizdev-05 commented on about.html
> +      </nav>
Great job adding the nav bar. 👍 
Kindly make sure that the nav has the same padding on both the left and right as we have it in the design.
| Behance Design | Your Design |
| :---:   | :---: | 
|<img width="1201" alt="image" src="https://user-images.githubusercontent.com/73854999/225427795-da5069cf-e085-4dd2-ad68-2d3c6043b448.png"> | <img width="1458" alt="image" src="https://user-images.githubusercontent.com/73854999/225427264-28e1fc72-da4c-4577-a8f8-6fa25398d354.png">|

2023-03-15 20:19 UTC, Lizdev-05 commented on about.html
> +    <p class="lead mb-4 text-center">Welcome to our Ruby on Rails Bootcamp! This intensive program is designed to equip you with the knowledge and skills needed to build robust web applications using
Kindly align the text to the center with the appropriate padding and margin so as to have the same styling as what we have in the Behance template. 📦 🥺 
| Your Design | Figma Design |
| :---:   | :---: | 
|<img width="1336" alt="image" src="https://user-images.githubusercontent.com/73854999/225428410-245998ae-6235-4c78-af7a-cf359063be31.png"> |<img width="1063" alt="image" src="https://user-images.githubusercontent.com/73854999/225428512-513d23fa-c88c-4f55-9c21-55b4b955501c.png"> |

2023-03-15 20:19 UTC, Lizdev-05 commented on about.html
> +            <img class="btcp-img" src="./assets/prev_bootcamps/lagos.png" alt="Previous bootcamp image">
Great job on using your initiative to create a logo 👍 . I think it will be much better and in line with the Behance design if you reduce the height of the box 😊

2023-03-15 20:19 UTC, Lizdev-05 commented on about.html
> +        </div>
Kindly centralize these two cards and increase the width a bit so we can have the same design as the Behance template 🥺 
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/73854999/225429408-c6a7a9eb-ca03-46dd-b6d4-2205ce618cc9.png">


on a mobile screen of 375 upward, your cards are left aligned, kindly centralized in line with the requirement
| Your Design | Figma Design |
| :---:   | :---: | 
|<img width="553" alt="image" src="https://user-images.githubusercontent.com/73854999/225430631-53c0d4ba-8977-44ad-9807-0ba9d6561151.png"> | <img width="553" alt="image" src="https://user-images.githubusercontent.com/73854999/225430558-5448a1e5-573e-4061-852e-f4f46669b58d.png">|

2023-03-15 20:19 UTC, Lizdev-05 commented on about.html
> +  </footer>
Kindly give your footer the necessary padding and margin. 🥺 
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/73854999/225429742-cf09360d-ae4b-4df6-8a9f-6f69894516cb.png">

Also, according to the requirement, your footer should contain a logo at the left and text at the right. Kindly add the logo and the necessary stylings. 🥺

2023-03-15 20:19 UTC, Lizdev-05 commented on index.html
> +    <div>
On the mobile display, the speakers' images does not have the background pattern like what we have in the Behance template, kindly include it because this is part of the requirements.
<img width="395" alt="image" src="https://user-images.githubusercontent.com/73854999/225431949-429cdb9a-a8fc-4466-a78e-d55a39948ab7.png">

2023-03-16 15:37 UTC, BregornOriginal requested changes
## Hi @adeola003  

## Good job so far!

There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![one-step-closer-one-more](https://user-images.githubusercontent.com/93630700/225666979-da1ac2f3-42e0-4754-8a5e-d84ee02025a7.gif)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-16 15:37 UTC, BregornOriginal commented on README.md
> +- [https://adeola003.github.io/Ruby-on-rails-bootcamp/](#)
Good work implementing the requested changes by the previous reviewer 💯 💯 💯 

- As the last thing to approve, kindly add the corresponding link to the live version of your project. This means a link to the deployed website that you have created 🥇

2023-03-16 15:57 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 16:00 UTC, merged